-- Migration: Add is_ai_generated field to recipes table
-- This field tracks whether a recipe was generated by AI

-- Add is_ai_generated column to recipes table
ALTER TABLE recipes 
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT false;

-- Set default value for existing recipes (they are not AI-generated)
UPDATE recipes 
SET is_ai_generated = false 
WHERE is_ai_generated IS NULL;

-- Add comment to document the field
COMMENT ON COLUMN recipes.is_ai_generated IS 'Indicates whether the recipe was generated by AI (e.g., via Gemini)';

